facebookexperimental/Recoil

docs/docs/api-reference/core/useRecoilState.md

fixed a typo in docs for useRecoilState example

docs: fix typo

---

docs/docs/api-reference/utils/atomFamily.md

Replaced "familyAtom()" with "atomFamily()".

Fixed typo in atomFamily.md

---

docs/docusaurus.config.js

👋 team,
I am working on DocSearch. [We have an integration for Docusaurus](https://docusaurus.io/docs/en/search#enabling-the-search-bar). We thought it is a shame you can not also used this search that you can [find on reactjs for example](https://reactjs.org/).
This PR will add DocSearch to the documentation website. It will allow an user to have a learn-as-you-type experience by displaying results thanks to a dropdown in a live way.
Let me know if you need anything.

feat(website): add DocSearch as recommended by docusaurus

---

.babelrc
package.json
src/adt/__tests__/Recoil_ArrayKeyedMap-test.js
src/caches/__tests__/Recoil_cacheMostRecent-test.js
src/caches/__tests__/Recoil_cacheWithReferenceEquality-test.js
src/caches/__tests__/Recoil_cacheWithValueEquality-test.js
src/core/__tests__/Recoil_RecoilValueInterface-test.js
src/core/__tests__/Recoil_core-test.js
src/hooks/__tests__/Recoil_PublicHooks-test.js
src/hooks/__tests__/Recoil_useRecoilCallback-test.js
src/hooks/__tests__/Recoil_useRecoilInterface-test.js
src/hooks/__tests__/Recoil_useRecoilStateReset-test.js
src/hooks/__tests__/Recoil_useRecoilValueLoadable-test.js
src/recoil_values/Recoil_WaitFor.js
src/recoil_values/Recoil_error.js
src/recoil_values/__tests__/Recoil_WaitFor-test.js
src/recoil_values/__tests__/Recoil_atom-test.js
src/recoil_values/__tests__/Recoil_atomFamily-test.js
src/recoil_values/__tests__/Recoil_atomWithFallback-test.js
src/recoil_values/__tests__/Recoil_constSelector-test.js
src/recoil_values/__tests__/Recoil_errorSelector-test.js
src/recoil_values/__tests__/Recoil_selector-test.js
src/recoil_values/__tests__/Recoil_selectorFamily-test.js
src/testing/Recoil_TestingUtils.js
src/util/__tests__/Recoil_stableStringify-test.js
yarn.lock

This PR adds a test script to package.json, adding a few bits and bobs to ensure jest can parse Flow typed JS and modules are correctly resolved according to the aliases:
FB module name | OSS module name
------------ | -------------
React | react
ReactDOM | react-dom
ReactTestUtils | react-dom/test-utils
The PR also adds the `install-peers` dev dependency described in Yvonnick Frin's [post on dev.to](https://dev.to/yvonnickfrin/how-to-handle-peer-dependencies-when-developing-modules-18fa).
[fb-only] If you're a Facebook employee, the full test output is captured for your convenience at P131376227.

feature(test): Adds jest as test script

---

docs/docs/guides/asynchronous-data-queries.md

userID is not being used in the selector body, I assume that it should not be included in the examples

[docs] removed "userID" from selector

---

package.json
rollup.config.js
scripts/postbuild.js
src/npm/index.js

Based off of #67 to avoid conflicts.
This fixes an issue that was breaking a fresh create-react-app from working, due to CRA's own minification step running only in production mode.
Demo repo is [here](https://github.com/dustinsoftware/recoil-playground/tree/094862e722ec6ed016d4b723061df77c7db65fb3), run `yarn build && npx serve build` to see the isuse.

Disable variable name mangling in terser

---

docs/docs/introduction/core-concepts.md

Without parantheses component repeatedly rerender itself and this causes a "Maximum update depth exceeded" error.

[docs] Added parentheses to onClick function

---

docs/docs/guides/asynchronous-data-queries.md

May be that it was status before but right now getting the current state of the useRecoilValueLoadable
is done via the `state` field instead of `status`

[docs] Changed fieldname for useRecoilValueLoadable hook

---

README.md

Show the status of the official build rather than @dustinsoftware's, and make it link to the actions page rather than just showing the badge image on click.

Fix badge URL in README

---

package.json
yarn.lock

Adds `lint-staged`, which will format all staged files using Prettier. This means you can't accidentally commit unformatted files. We can also add other linters to this (e.g. ESLint) later on.
I also removed `jsx` from the file pattern since the repo doesn't contain JSX files.
An example commit with `lint-staged`:

Adds lint-staged

---

docs/docs/guides/asynchronous-data-queries.md
docs/docs/guides/asynchronous-state-sync.md

[docs] initial docs for syncing state

---

docs/docs/guides/asynchronous-data-queries.md
docs/docs/guides/asynchronous-state-sync.md

Address some feedback from #159

[docs] feedback from PR159

---

docs/docusaurus.config.js

According to the documentation (https://v2.docusaurus.io/docs/blog#feed) only a small config update is needed.

Enable RSS & Atom feeds for blog

---

docs/docs/introduction/installation.md

[docs] recommends adding  'useRecoilCallback' to eslint config

---

docs/docs/api-reference/core/selector.md

The setter function is defined as SetRecoilState, but the selector's
options.set type is SetRecoilValue which I do not see defined anywhere.
Note: I still feel SetRecoilValue is better as it matches what it does
and mirrors GetRecoilValue. Additionally, the useSetRecoilState() hook
should be renamed to useSetRecoilValue() to match useRecoilValue().
Given the typo this commit fixes, I am not alone. :)

Fix selector() options "set: SetRecoilValue" type to "SetRecoilState"

---

docs/docs/api-reference/core/useRecoilCallback.md
docs/docs/api-reference/core/useRecoilStateLoadable.md
docs/docs/api-reference/core/useResetRecoilState.md

Only three of the seven sidebar links for the Hooks include their parameters.
To keep the sidebar readable--especially once you inevitably add a hook
with more than one parameter--omit all parameters.

Remove parameters from Hooks sidebar links

---

docs/docs/api-reference/core/selector.md

As I was reading through the documentation, I noticed a small one letter typo on the asynchronous example of the `api-reference/core/selectors()`. 
The small typo was `neValue` in line 136.
Hope this helps, I really didn't see an issue for it, but if there are any other steps I need to take to submit a PR please let me know :)

Fix typo in selector.md example

---

docs/docs/basic-tutorial/selectors.md

seems like we'd want the stats on the full todoList, not on the filtered list.
otherwise you click on "unfinished" and the stats say that you're 0% complete, then you click on "finished" and the stats say 100% complete.

[docs] use full todoList for stats, not filteredTodoList.

---

docs/docs/api-reference/core/useRecoilState.md

The definition of "state" included an extra unnecessary word.

Fix typo in useRecoilState.md description

---

docs/docs/api-reference/core/useResetRecoilState.md

looks like `useResetRecoilState` setter call  will not trigger component re-rendering. 
I did not have a chance to validate it, but I sure it's true.
I propose to add the same phrase as in https://recoiljs.org/docs/api-reference/core/useSetRecoilState about re-rendering
In case if I'm wrong please decline the PR and possible it could be the reason to fix the behaviour since from API-usage point both setters  (`useResetRecoilState`, `useSetRecoilState`)are the same.

[docs] Update useResetRecoilState.md

---

docs/docs/api-reference/core/useSetRecoilState.md

Based on docs description component depends on `useSetRecoilState` will not be re-render on call of its setter
In the example was used only one component depends on `useState` hook and also will raise `onClick` what means the component renders happens each time on different triggers (click/change/call setters)
To clarify phrase `Using `useSetRecoilState()` allows a component to set the value without re-rendering when the value changes.` I propose to  move all dynamic part to the child component and pass to it recoil setter to split different re-rendering triggers to children and let root component depends only on the recoil setter.

[docs/example] Update useSetRecoilState.md

---

docs/docs/api-reference/core/selector.md

current example with async selector is not clear, since without inner await we could remove `async` prefix and directly return callback's result if the result is a promise
```
get: async () => {
return myDBQueryPromise();
}
```
will be the same
```
get: () => myDBQueryPromise()
```
or to be sure to work with promises always simple wrap the result `get: () => Promise.resolve(myDBQueryPromise())`
to avoid possible misunderstanding I propose to add `await` in the callback's body to highlight `async` root of the get callback
The result:
```
get: async () => {
const queryResults = await myDBQueryPromise();
// other dependent operations
return queryResults;
}
```

[docs/example] Update selector.md async example

---

docs/docs/api-reference/utils/noWait.md

This PR fixes the error in the example code of `noWait()` function.

Fix: errors in the example code of noWait()

---

docs/docs/api-reference/core/Snapshot.md

Should the correct text of this section be as follows?
[...] It is intended to standardize the API for observing, inspecting, and managing global Recoil state.  It is mostly useful for dev tools, global state synchronization, history navigation, etc.

Class Snapshot Text

---

docs/docs/guides/asynchronous-state-sync.md
docs/docs/guides/persistence.md

fix to navigate right (before: [Page Not Found](https://recoiljs.org/docs/guides/persistence/asynchronous-state-sync))

[Docs] Fix mis-located inner links in persistence/asynchronous-state-sync

---

docs/docs/guides/testing.md

**Summary**
There is an error because the variable is wrong.
`initialSnapshot`, `testSnapshot` and `mySnapshot` should be changed correctly.

fix: snapshot variable is not defined

---

docs/docs/guides/asynchronous-data-queries.md

Recoil is looking very cool! Excited to use it where traditionally we might have reached for Redux or custom context...
I was just going through the latest docs and noticed a small typo on async queries showing `userRecoilValue` instead of `useRecoilValue`.

[docs] async fix typo userRecoilValue

---

docs/docs/api-reference/core/atom.md
docs/docs/api-reference/core/selector.md
docs/sidebars.js

Flatten the API reference and adjust structure slightly to better emphasize more important topics.

[docs] Flatten API Reference

---

docs/docs/guides/atom-effects.md

Asynchronous / Promise examples of Local Storage Persistence
https://github.com/facebookexperimental/Recoil/issues/767

More examples of Local Storage Persistence

---

docs/docusaurus.config.js

Got this message from `yarn build`
```
error building locale=en
Error: Plugin docusaurus-plugin-google-analytics is used 2 times with id=default.
To use the same plugin multiple times on a Docusaurus site, you need to assign a unique id to each plugin instance.
at /Users/mengdi/workspace/github/Recoil/docs/node_modules/@docusaurus/core/lib/server/plugins/pluginIds.js:20:23
```
We didn't have this before -- might be a result of upgrading docusaurus in #932 
According to https://github.com/facebook/docusaurus/issues/3632#issuecomment-716596075
> If you use the classic preset with googleAnalytics themeConfig, you already use the google analytics plugin, as it's included in the preset.
we should remove the GA plugin from our config file to resolve this.
After removing this line, the build is …

fix build script error of docs site

---

docs/docs/guides/asynchronous-data-queries.md

The missing, declaration is in the Use a Request Id section of the docs.

[Docs]: Add missing 'const' in 'userRefreshInfo' function

---

docs/docs/api-reference/core/RecoilRoot.md
docs/docs/api-reference/core/selector.md

DO NOT LAND UNTIL AFTER RELEASE
* selector `getCallback()`
* `overload` prop in `<RecoilRoot>`

Docs for 0.3.0 release

---

docs/docs/api-reference/core/selector.md
docs/docs/api-reference/utils/selectorFamily.md

Adds documentation for the upcoming `cachePolicy_UNSTABLE` API addition to selectors.

Add cachePolicy_UNSTABLE to docs

---

docs/blog/2021-03-22-0.2.0-released.md
docs/blog/2021-05-14-0.3.0-released.md
docs/blog/2021-07-30-0.4.0-release.md
docs/docs/api-reference/core/selector.md
docs/docs/api-reference/core/useRecoilCallback.md
docs/docs/api-reference/core/useRecoilTransaction.md
docs/docs/api-reference/utils/selectorFamily.md
docs/docs/guides/asynchronous-data-queries.md
docs/docs/guides/atom-effects.md
docs/docs/introduction/installation.md
docs/sidebars.js

* Release notes
* `useRecoilTransaction_UNSTABLE()`
* Breaking changes for Atom Effect `onSet()`
* `cachePolicy_UNSTABLE` - See also #1139

Documentation for 0.4

---

docs/docs/api-reference/core/useRecoilCallback.md

In practice, I expect that much of the motivation for using `useRecoilCallback()` is to avoid recreating a callback when a Recoil value changes, as the callback will always read the latest value via the `snapshot` when it is executed. As I understand it, like `useCallback()`, if `deps` is not specified, a new callback will get created on each render of the React component, which is not desirable. This is results in extra computation and can cause unnecessary re-renders of child components to which the callback is passed.

Update example to specify [] for the deps.

---

docs/docs/api-reference/core/useRecoilTransaction.md

There are typos in [Transaction Example](https://recoiljs.org/docs/api-reference/core/useRecoilTransaction#transaction-example).

[docs] fix typos in `useRecoilTransaction`

---

docs/docs/guides/testing.md

I fixed the wrong code in `testing.md` for `RecoilObserver`.

Fix missing bracket in `testing.md` for `RecoilObserver`

---

docs/docs/api-reference/core/selector.md

The exclusion of an 'identifier' made it difficult to comprehend a sentence.

typo: correct typo in selector.md

---

docs/docs/guides/testing.md

Per #1522, include an example of how to test a custom hook that relies on Recoil states. This example uses React Hooks Testing Library

[docs] Document custom hooks that use Recoil states

---

docs/i18n/ko/docusaurus-plugin-content-docs/current/guides/atom-effects.md

- Due to [Recoil 0.6 Documentation release](https://github.com/facebookexperimental/Recoil/commit/9932f5e43056ea8d9f77816fde778800fd896582#diff-33b7a54bcbd3c5dce0fc9f70d50de2e2a9260d9865c0a890252b2d92bb9d668e/docs/docs/guides/atom-effects.md), korean docs were also updated. (Ex. from: `effects` -> to: `effects_UNSTABLE`)
- Fix awkward korean translation

[docs/korean] update legacy translation to latest content

---

docs/i18n/ko/docusaurus-plugin-content-docs/current/guides/testing.md

- Added korean translation of [guides/testing](https://recoiljs.org/docs/guides/testing) page.

[docs/korean] add korean translation of [Guides/Testing] documentation

---

docs/docs/guides/testing.md

I wasn't sure if it's necessary to create a complete second example since they're _mostly_ equal in code. Right now it only references the already existing documentation but if you prefer an example with a new headline just let me know, I originally prepared one:
```js
export const numberState = atom({
key: "number",
default: selector({
key: "number/Default",
get: async () => {
// await some numbers
}
})
});
test('Test async numberState default', async () => {
const initialSnapshot = snapshot_UNSTABLE();
initialSnapshot.retain();
await expect(initialSnapshot.getLoadable(numberState).promiseOrThrow()).resolves.toBe(0);
});
```
This could also link to the existing docs for a more complete picture of retain/release handling
Closes #1590

Add note about retaining a snapshot in async selector jest tests

---

docs/docs/guides/testing.md

- Fixes variable name passed to `RecoilObserver.node` to match the earlier example.
- Drop "Jest" from the async selector title as it's not specific to Jest
- Make clear `retain()` needs to be followed by `release()`.
- Explain why we need to clear cache.
- Show how to clear cache in `afterEach` for Jest

Improve test guide

---

docs/i18n/ko/docusaurus-plugin-content-docs/current/api-reference/core/useRecoilRefresher.md

Currently, there is no "useRecoilRefresher.md" file translated into Korean, so it was produced.
If you access "https://recoiljs.org/ko/docs/api-reference/core/useRecoilRefresher/", it's the English version.

[docs/korean] add translate useRecoilRefresher.md to Korean

---

docs/i18n/ko/docusaurus-plugin-content-docs/current/basic-tutorial/selectors.md

Hello, I'm looking at the [Recoil Selectors page](https://recoiljs.org/ko/docs/basic-tutorial/selectors/),  but There's a typo and I think there's no emphasis on words, so I'm posting PR.
1. fix typo: toListFilterState -> todoListFilterState
Add double quotes to show All -> "show All' (This is because double quotes are added to the English document.)
2. Emphasize words(state, option) : 'todoListFilterState' , 'Show All'   (Because it is highlighted in the English document.)

[docs/korean] fix typo and  highlighted words

---

docs/i18n/ko/docusaurus-plugin-content-docs/current/basic-tutorial/selectors.md

Fix wrong typo. 
'toDoListStatsState' -> `todoListStatsState`

[docs/korean] Fix typo

---

docs/docs/recoil-sync/api/RecoilURLSyncTransit.md

[docs] Fix typo in RecoilURLSyncTransit example

---

docs/docs/recoil-sync/api/RecoilSync.md

Documents #2035. Relates to #2017

[docs] Expose updateItems in RecoilSync's Listen Interface

---

docs/docs/recoil-relay/graphql-queries.md

In the [GraphQL Query with Parameters](https://recoiljs.org/docs/recoil-relay/graphql-queries#graphql-query-with-parameters) section s/basd/based/

Fix a typo in GraphQL Query with Parameters documentation

---

packages/recoil-relay/RecoilRelay_graphQLSelector.js

Summary:
Small tweak in the type definition of `graphQLSelector` (RecoilRelay_graphQLSelector.js) to avoid Flow errors in the new LTI mode.
Context: https://fb.workplace.com/groups/flow/posts/24417786084510010/?comment_id=24439307842357834&reply_comment_id=24440084235613528
Reviewed By: kartmanny
Differential Revision: D44190433

small change in type of graphQLSelector

---

packages/shared/__test_utils__/Recoil_TestingUtils.js

Summary:
Update type definition of ReactDOMLegacy_DEPRECATED.render to include required `sourceFileName` argument.
This diff is also adding these names to places not covered by previous diffs.
---
Context:  We (React Team) is working on modernizing  Meta codebase, and replacing legacy and deprecated React APIs with Modern (use createRoot + render vs ReactDOM.render).
This diff adds an argument to the legacy render method with explicit file name. We'll be tracking the usage of these legacy renderers and migrate the most used callsites.
Reviewed By: kassens
Differential Revision: D44271426

Make source file name required argument of ReactDOMLegacy_DEPRECATED.render(...)

---

packages/recoil/recoil_values/Recoil_atom.js
packages/recoil/recoil_values/__tests__/Recoil_atom-test.js
packages/recoil/recoil_values/__tests__/Recoil_selector-test.js

There was a problem with not waiting for an atom initialized by promise when used in a selector with another selector. I described details in the related issue. I also created a repro on [codesandbox](https://codesandbox.io/s/recoil-issue-with-promise-effect-l6ddpd?file=/src/App.js).
The PR adds code suggested by @drarmstr in this [comment](https://github.com/facebookexperimental/Recoil/issues/2151#issuecomment-1491111260).
I tested this and it helps with the issue. I created a unit test but it doesn't work correctly. See my [comment here](https://github.com/facebookexperimental/Recoil/issues/2151#issuecomment-1502668034)
Related to https://github.com/facebookexperimental/Recoil/issues/2151

fix: atom initialized by promise updates downstream selectors

---

packages/recoil-sync/__tests__/RecoilSync_URLCompound-test.js

Instead of using `setConcurrentMode` directly, use `testRecoil` to make sure it runs with correct versions of React

use testRecoil in RecoilSync_URLCompound

---

packages/recoil/core/Recoil_RecoilRoot.js
packages/recoil/core/Recoil_State.js
packages/recoil/recoil_values/Recoil_selector.js

Summary:
I discovered a bug in `detectCircularDependencies()` where it may erroneously detect a circular dependency when `graphQLQueryEffect()` is used. It arises from the fact that we are using a global stack to keep track of which Atom/Selectors have been *visited*.
From the stack trace, I think I've figured out what is happening...
1) There are a bunch of `selectorGet()` calls to load dependencies.
2) This calls `detectCircularDependencies()` several times and a bunch of keys get added to the `dependencyStack`, as you would expect. So far, everything looks good.
3) Then, because it is a nested dependency, we load an Atom that has a `graphQLQueryEffect()`.
4) The `graphQLQueryEffect()` subscribes to a `RelayObservable`.The act of subscribing schedules a task using the …

Add flag to skip circular dependency detection

---

packages-ext/recoil-devtools/src/pages/Popup/Items/ItemLabel.js
packages-ext/recoil-devtools/src/pages/Popup/Items/NodeName.js

Summary:
This diff cleans up the final batch of leftover `React.Element<'div'>` and `React.Element<'span'>`. These specific types usually serves no purpose for both style and runtime.
Since the number of remaining uses of these types are small, I finally discovered the potential reason of their widespread uses. Some widely used template (the initial stub filled in by VSCode) uses these types:
https://www.internalfb.com/code/www/scripts/comet/components/Component.react.js.template?lines=24
Therefore, I also fixed these templates to use `React.MixedElement` instead.
Differential Revision: D45782223

Replace most of the `React.Element<'div'>` and `React.Element<'span'>` with `React.MixedElement` in www

---

packages/recoil/adt/Recoil_Loadable.js

Summary:
Suppress existing errors currently on Flow master build. This diff allows the diff after this D45996637 to only deal with a single issue, so we can provide better comments in suppressions.
drop-conflicts
Differential Revision: D45995993

Pre-suppress errors for Flow 0.207.0 release

---

packages/recoil/core/Recoil_RecoilRoot.js

Summary:
Wraps the ReactRoot internally in a React Suspense boundary as Recoil uses `useEffect` in ways to do automatic batching that's not compatible with React 18 in case the Root suspends itself.
The reason for this is that with React 18, the `useEffect` callback is only called one the component is actually getting displayed. If the `useEffect `callback itself is what makes the component eventually un-suspend it causes an infinite suspense.
This isn't an ideal solution, but I'm not deep enough into Recoil to be able to propose a better solution.
Reviewed By: mrv1k
Differential Revision: D46405179

RecoilRoot is also a Suspense boundary

---

packages/recoil/core/Recoil_RecoilRoot.js

Summary: Unclear why this was added with D23056388. Seems like it was "just in case" this API is bad? Logs don't turn up any errors though.
Reviewed By: mrv1k
Differential Revision: D46444484

remove unnecessary try/catch from RecoilRoot

---

packages/recoil/hooks/Recoil_SnapshotHooks.js
packages/recoil/recoil_values/__tests__/Recoil_atomFamily-test.js
packages/recoil/recoil_values/__tests__/Recoil_selectorFamily-test.js

Differential Revision: D46545937

Format out of sync files

---

packages/recoil/core/Recoil_ReactMode.js
packages/recoil/core/Recoil_RecoilRoot.js
packages/recoil/core/Recoil_RecoilValueInterface.js
packages/recoil/core/Recoil_State.js
packages/recoil/hooks/Recoil_Hooks.js
packages/recoil/hooks/Recoil_useRecoilBridgeAcrossReactRoots.js
packages/recoil/hooks/__tests__/Recoil_React-test.js
packages/recoil/hooks/__tests__/Recoil_useRecoilBridgeAcrossReactRoots-test.js
packages/recoil/hooks/__tests__/Recoil_useTransition-test.js
packages/recoil/recoil_values/__tests__/Recoil_selectorHooks-test.js
packages/shared/__test_utils__/Recoil_TestingUtils.js

Summary:
Reaps the GK to use `useMutableSource` in Recoil. While the GK is at 100%, it's never hit as we hit the check for `recoil_sync_external_store` before and that's also 100%.
`useMutableSource` is deprecated in React and this is one of the last callers.
Differential Revision: D47023855

reap test recoil_mutable_source
