facebookexperimental/Recoil

- docs/docs/basic-tutorial/selectors.md
~~isComplete -> isCompleted~~
isCompleted -> isComplete
> docs: correct variable name in sample code

- docs/docs/introduction/core-concepts.md
> correct a text

- README.md
This is an interesting project!
I've sent a PR to use an https link instead of an http link.
> docs: use https for the website instead of http

- docs/docs/guides/asynchronous-data-queries.md
> docs: fix async function usage

- docs/src/pages/index.js
It has the great Q&A at the end
> Use React Europe video

- docs/docs/basic-tutorial/atoms.mdx
Just an additional update for the `addItem` function.
> Update `TodoItemCreator` in the examples

- src/util/Recoil_isNode.js
Fixes https://github.com/facebookexperimental/Recoil/issues/34
> Avoid window reference error in SSR

- package.json
- rollup.config.js
- scripts/postbuild.js
- src/npm/index.js
This should work on Windows too.
Tested with `yarn link` on a local project.
Fixes #61
> Add development build

- src/recoil_values/Recoil_atom.js
as mention above, fix selector reference in the atom
> fix selector reference

- src/adt/Recoil_Loadable.js
- src/core/Recoil_Node.js
- src/core/Recoil_State.js
- src/recoil_values/Recoil_ScopedAtom.js
- src/recoil_values/Recoil_WaitFor.js
- src/recoil_values/Recoil_atom.js
- src/recoil_values/Recoil_selector_NEW.js
- src/util/__tests__/Recoil_stableStringify-test.js
> nit/fixing-misspelling - Fixing minor misspelling

- src/components/Recoil_Link.react.js
- src/hooks/Recoil_Hooks.js
Changes: compoment -> component
> Fix minor misspelling

- docs/docs/api-reference/core/useSetRecoilState.md
**Overview:**
This is simply to add an example for `useSetRecoilState` hooks in [API Reference](https://recoiljs.org/docs/api-reference/core/useSetRecoilState/)
> [docs] Update description and add example for useRecoilValue()

- docs/docs/api-reference/core/useResetRecoilState.md
Hi 👋🏼
I created a sample code for useResetRecoilState()
> [docs] edit content for useResetRecoilState() page

- .github/workflows/nodejs.yml
- README.md
Fixes #66 
After tests are passing, add `yarn test` to the end of `nodejs.yml`.
In testing this I noticed an oversight in #67 where during `yarn publish` a few files were missing from the dist folder. This is addressed in this PR.
> GitHub actions

- docs/docs/introduction/core-concepts.md
> [docs] Add missing dot

- .flowconfig
- package.json
closes #115 
Have I forgotten something in config file?
PS Also I wanted to change `build` script to also run flow before it runs rollup, but currently we have ~160 flow issues, so I didn't do it.
> fix(flow): Add flow configuration file

- docs/docs/guides/persistence.md
- docs/docs/guides/persistence.mdx
Hello, I added some basic example and documentation about persistence because there is none right now and you have to deep into the code to understand how to do it.
> [docs] document persistence.

- docs/docs/guides/asynchronous-state-sync.md
> [docs] Fix bi-directional syncing example

- docs/docs/api-reference/core/useRecoilCallback.md
> [docs] Improve docs for useRecoilCallback

- docs/docs/basic-tutorial/performance.md
> Fix a tiny typo in the tutorial

- docs/docs/api-reference/core/useRecoilCallback.md
interace -> interface
ascynrhonous -> asynchronous
> Fix tiny typos on useRecoilCallback.md

- docs/docs/guides/asynchronous-data-queries.md
get is not used, so I guess it can be removed?
> [docs] Asynchronous Example - remove unused get in selectorFamily

- docs/docs/basic-tutorial/selectors.md
> [docs] fix typo in selectors.md

- docs/docs/api-reference/core/selector.md
I added a period and two commas in the first paragraph.
> Minor grammar (missing period, commas)

- docs/docs/api-reference/utils/constSelector.md
- docs/docs/api-reference/utils/errorSelector.md
- docs/docs/api-reference/utils/noWait.md
- docs/docs/api-reference/utils/waitForAll.md
- docs/docs/api-reference/utils/waitForAny.md
- docs/docs/api-reference/utils/waitForNone.md
> [docs] Remove parameters from utils API in sidebar

- docs/docs/guides/persistence.md
> [docs] Fix a couple issues in persistence.md

- docs/docs/api-reference/utils/atomFamily.md
> [docs] Improve atomFamily example with selectorFamily default

- docs/docs/api-reference/utils/selectorFamily.md
> [docs] Add destructuring example to selectorFamily docs

- docs/docs/api-reference/core/useRecoilCallback.md
- docs/docs/guides/asynchronous-data-queries.md
> [docs] Document Pre-Fetching example

- docs/blog/2020-06-18-0.0.10-released.md
> fix: initializeState example type

- docs/docs/guides/asynchronous-data-queries.md
Hello,
First, thank you for the amazing concept and hard work done in this library.
Sorry if this is bothering you, but as I was ridding the (very nice) documentation, I came across this example and thought it could be improved, by reducing (just a little bit) the number of lines of code.
Do you think this can bring a bit more clarity, and thus emphasis on the core concepts? 
Thanks for your answer, keep it up!
> refactor: small simplification in code example

- docs/docs/api-reference/utils/selectorFamily.md
- docs/docs/guides/asynchronous-state-sync.md
Hello guys. I've just started to investigate Recoil. Thank you for your work; I really love it.
During reading Recoil docs I found some incompatibilities of the coding style of some examples. So, I didn't add new rules (which I would like to do), I just made them look similar; in some code segments, you forgot semicolons and trailing commas. Unfortunately, the process of checking was manual.
> Coding style corrections

- docs/docs/guides/asynchronous-data-queries.md
> [docs] Fix query refresh example

- docs/docs/basic-tutorial/selectors.md
The name `percentCompleted` hints on it being a percent and so the code should reflect that. Otherwise it would be something like "progress".
> Name of variable `percentCompleted` should reflect its value in selectors.md

- docs/docs/api-reference/core/RecoilRoot.md
- docs/docs/api-reference/core/Snapshot.md
Add a trivial example of using `initializeState` prop for `<RecoilRoot>`
> [docs] Add initializeState example

- docs/docs/guides/dev-tools.md
> update example codes about Dev Tools

- docs/docusaurus.config.js
- docs/src/pages/resources.js
> Add an "External Resources" Page

- docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/core-concepts.md
Corrected the typo and corrected some sentences to make it more natural in Korean.
> [docs/korean] Update core-concepts.md in KOR

- docs/i18n/ko/docusaurus-plugin-content-docs/current/introduction/installation.md
Translate content and modify it for more natural interpretation in Korean.
> [docs/korean] Update installation.md in KOR

- docs/i18n/ko/docusaurus-plugin-content-docs/current/api-reference/core/useGetRecoilValueInfo.md
> [docs/korean] Update useGetRecoilValueInfo.md

- docs/docs/basic-tutorial/intro.md
Add a missing period to the last sentence.
> Fix typo in intro.md

- docs/blog/2021-03-22-0.2.0-released.md
- docs/blog/2021-05-14-0.3.0-released.md
> 0.3.0 blog post

- docs/i18n/ko/docusaurus-plugin-content-docs/current/guides/asynchronous-data-queries.md
- Translate asynchronous-data-queries document to Korean
add new translations in asynchronous-data-queries.md
: There were some missing parts
> [docs/korean] fix missing translations

- docs/i18n/ko/docusaurus-plugin-content-docs/current/guides/asynchronous-data-queries.md
> [docs/korean] Fix a typo

- docs/i18n/ko/docusaurus-plugin-content-docs/current/api-reference/core/useRecoilBridgeAcrossReactRoots.md
> doc: fix typo

- docs/i18n/zh-hans/docusaurus-plugin-content-docs/current/api-reference/core/selector.md
修改错误变量
modify wrong variable
selector -> selectorA
> Update selector doc

- docs/docs/guides/testing.md
Minor polish for new guide on testing from @timbergus #1198
> [docs] Testing guide polish

- docs/i18n/fr/docusaurus-plugin-content-docs/current/introduction/getting-started.mdx
spelling mistake in the french version of getting-started.mdx
> getting-started.mdx spelling mistake

- docs/i18n/fr/docusaurus-plugin-content-docs/current/basic-tutorial/atoms.mdx
spelling mistakes in atoms.mdx file
> french spelling mistakes

- docs/docs/guides/testing.md
Adds documentation for the discussion on #1457
> Update testing.md with asynchronous default atom

- docs/docs/guides/asynchronous-data-queries.md
> [docs] Add more examples for querying atom defaults.

- docs/docs/guides/asynchronous-data-queries.md
Missing return statement in QueryErrorMessage example
> Fixed example at asynchronous-data-queries.md

- docs/docs/basic-tutorial/selectors.md
Improved phrasing for better understanding. The phrase '..modifies the given state in some way..'  is confusing, because it seems to imply that some 'state' is being modified, which is not the case. Whereas, '...derives a new value from the said state...' seems more clear.
> Improved phrasing.

- docs/i18n/zh-hans/docusaurus-plugin-content-docs/current/guides/asynchronous-data-queries.md
This fix was reverted unexpectedly by 6fbf602 😂
Previous PR #1303
> docs: fix "fallback" translation

- docs/docusaurus.config.js
- docs/src/css/custom.css
Our mission at [Meta Open Source](https://opensource.facebook.com/) is to empower communities through open source, and we believe that it means building a welcoming and safe environment for all. As a part of this work, we are adding this banner in support for Ukraine during this crisis.
> docs: add social banner in support of Ukraine 

- docs/docs/basic-tutorial/atoms.mdx
- docs/docs/basic-tutorial/selectors.md
> [docs] Use distinct key strings in Basic Tutorial

- docs/docs/recoil-relay/graphql-effects.md
`graphQLMutatonEffect` -> `graphQLMutationEffect`
> docs: fix typo

- docs/i18n/ko/docusaurus-plugin-content-docs/current/guides/atom-effects.md
> [docs/korean] fix typo

- docs/src/pages/index.js
- docs/src/pages/styles.module.css
#1865 issue solved 
Edited Styles for the YouTube video iframe tags.
> Solved issue #1865

- docs/i18n/ko/docusaurus-plugin-content-docs/current/api-reference/core/useRecoilStoreID.md
translate https://recoiljs.org/docs/api-reference/core/useRecoilStoreID/ document to korean :D
> [docs/korean] Add useRecoilStoreID.md for translate korean

- docs/i18n/ko/docusaurus-plugin-content-docs/current/guides/transitions.md
translate to korean 👉 https://recoiljs.org/docs/guides/transitions/
> [docs/korean] translate guide/transition.md

- docs/i18n/ko/docusaurus-plugin-content-docs/current/api-reference/utils/waitForAllSettled.md
Hi!  😃
I update in [waitForAllSettled page - korean](https://recoiljs.org/ko/docs/api-reference/utils/waitForAllSettled).
Thank you.
> [docs/korean] update translate waitForAllSettled.md to Korean

- docs/i18n/ko/docusaurus-plugin-content-docs/current/guides/dev-tools.md
Hi ! 😁
I updated the [dev-tools](https://recoiljs.org/ko/docs/guides/dev-tools) mark-down file.
Please review :)
> [docs/korean] update translate dev-tools.md to Korean

- docs/i18n/ko/docusaurus-plugin-content-docs/current/basic-tutorial/intro.md
[Getting Started] -> [Recoil 시작하기]
> [docs/Korean] 📝intro.md

- docs/i18n/ko/docusaurus-plugin-content-docs/current/api-reference/core/useRecoilTransaction.md
Hello ! 😁
I updated the [dev-tools](https://recoiljs.org/ko/docs/api-reference/core/useRecoilTransaction) mark-down file.
Please review :)
> [docs/korean] update translate useRecoilTransaction.md to Korean

- docs/i18n/ko/docusaurus-plugin-content-docs/current/recoil-sync/introduction.md
translate to korean [recoil-sync/introduction](https://recoiljs.org/docs/recoil-sync/introduction)
> [docs/korean] create introduction.md in recoil-sync

- docs/i18n/ko/docusaurus-plugin-content-docs/current/api-reference/utils/atomFamily.md
update `atomFamily` docs Korean version
> [docs/korean] Update atomFamily docs

- docs/docs/api-reference/core/RecoilEnv.md
Partner PR to #2078 that documents the new functionality.
> [docs] Document the RECOIL_GKS_ENABLED env var

- docs/i18n/ko/docusaurus-plugin-content-docs/current/api-reference/core/RecoilEnv.md
added korean translation of api-reference/core/RecoilEnv.md
> [docs/korean] add korean translation of api-reference/core/RecoilEnv.md

- flow-typed/npm/react-dom_v18.x.x.js
Differential Revision: D44506265
> Asset Ownership Update For asset://code.file/www/scripts%2Frecoil%2F__github__%2Fflow-typed%2Fnpm%2Freact-dom_v18.x.x.js

- packages/recoil/core/__tests__/Recoil_RecoilRoot-test.js
- packages/recoil/core/__tests__/Recoil_RecoilValueInterface-test.js
- packages/recoil/core/__tests__/Recoil_Retention-test.js
- packages/recoil/core/__tests__/Recoil_Snapshot-test.js
- packages/recoil/core/__tests__/Recoil_perf-test.js
- packages/recoil/hooks/__tests__/Recoil_Hooks_TRANSITION_SUPPORT_UNSTABLE-test.js
- packages/recoil/hooks/__tests__/Recoil_PublicHooks-test.js
- packages/recoil/hooks/__tests__/Recoil_useGetRecoilValueInfo-test.js
- packages/recoil/hooks/__tests__/Recoil_useGotoRecoilSnapshot-test.js
- packages/recoil/hooks/__tests__/Recoil_useRecoilCallback-test.js
- packages/recoil/hooks/__tests__/Recoil_useRecoilRefresher-test.js
- packages/recoil/hooks/__tests__/Recoil_useRecoilSnapshot-test.js
- packages/recoil/hooks/__tests__/Recoil_useRecoilStateReset-test.js
- packages/recoil/hooks/__tests__/Recoil_useRecoilTransactionObserver-test.js
- packages/recoil/hooks/__tests__/Recoil_useRecoilValueLoadable-test.js
- packages/recoil/hooks/__tests__/Recoil_useTransactionObservation_DEPRECATED-test.js
- packages/recoil/recoil_values/__tests__/Recoil_WaitFor-test.js
- packages/recoil/recoil_values/__tests__/Recoil_atom-test.js
- packages/recoil/recoil_values/__tests__/Recoil_selector-test.js
- packages/recoil/recoil_values/__tests__/Recoil_selectorHooks-test.js
- packages/shared/__test_utils__/Recoil_TestingUtils.js
Reviewed By: SamChou19815
Differential Revision: D44526923
> Presuppress www errors for v0.203.0

- docs/i18n/ko/docusaurus-plugin-content-docs/current/guides/atom-effects.md
React effects 와도 유사하지만 -> React effects와도 유사하지만
> [docs/ko] fix typo

- packages/recoil-relay/RecoilRelay_graphQLSelectorFamily.js
- packages/recoil-sync/RecoilSync.js
- packages/recoil-sync/__tests__/RecoilSync_URLCompound-test.js
- packages/recoil/adt/Recoil_Loadable.js
- packages/recoil/core/__tests__/Recoil_RecoilRoot-test.js
- packages/recoil/core/__tests__/Recoil_RecoilValueInterface-test.js
- packages/recoil/core/__tests__/Recoil_Retention-test.js
- packages/recoil/core/__tests__/Recoil_Snapshot-test.js
- packages/recoil/core/__tests__/Recoil_perf-test.js
- packages/recoil/hooks/__tests__/Recoil_Hooks_TRANSITION_SUPPORT_UNSTABLE-test.js
- packages/recoil/hooks/__tests__/Recoil_PublicHooks-test.js
- packages/recoil/hooks/__tests__/Recoil_useGetRecoilValueInfo-test.js
- packages/recoil/hooks/__tests__/Recoil_useGotoRecoilSnapshot-test.js
- packages/recoil/hooks/__tests__/Recoil_useRecoilCallback-test.js
- packages/recoil/hooks/__tests__/Recoil_useRecoilRefresher-test.js
- packages/recoil/hooks/__tests__/Recoil_useRecoilSnapshot-test.js
- packages/recoil/hooks/__tests__/Recoil_useRecoilStateReset-test.js
- packages/recoil/hooks/__tests__/Recoil_useRecoilTransactionObserver-test.js
- packages/recoil/hooks/__tests__/Recoil_useRecoilValueLoadable-test.js
- packages/recoil/hooks/__tests__/Recoil_useTransactionObservation_DEPRECATED-test.js
- packages/recoil/recoil_values/Recoil_atom.js
- packages/recoil/recoil_values/__tests__/Recoil_WaitFor-test.js
- packages/recoil/recoil_values/__tests__/Recoil_atom-test.js
- packages/recoil/recoil_values/__tests__/Recoil_selector-test.js
- packages/recoil/recoil_values/__tests__/Recoil_selectorHooks-test.js
- packages/refine/Refine_Checkers.js
- packages/refine/Refine_ContainerCheckers.js
- packages/refine/Refine_PrimitiveCheckers.js
- packages/refine/Refine_UtilityCheckers.js
- packages/shared/__test_utils__/Recoil_TestingUtils.js
Reviewed By: mroch
Differential Revision: D45081285
> Daily removal of unused Flow suppressions

- packages/recoil/recoil_values/Recoil_atom.js
- packages/recoil/recoil_values/Recoil_selector.js
Summary: This diff suppresses errors uncovered by Flow v0.205.0
Reviewed By: SamChou19815
Differential Revision: D45337754
> Pre-suppression for deploying 0.205.0 to www

- .flowconfig
- package.json
- packages/shared/__test_utils__/Recoil_TestingUtils.js
- yarn.lock
Summary: Changelog: [Internal]
Differential Revision: D45464163
> Bump flow-bin to 0.205.0 to unbreak OSS CI

- .github/workflows/nodejs.yml
CI: remove Node.js 14, add Node.js 18
> CI: remove Node.js 14, add Node.js 18

- packages/recoil/core/Recoil_RecoilRoot.js
Summary: This has been launched. Cleanup the GK.
Reviewed By: RyanHoldren
Differential Revision: D47189406
> cleanup recoil_suspense_warning test

- packages/recoil/core/__tests__/Recoil_Retention-test.js
Differential Revision: D49064404
> presuppress Recoil Flow error for Flow 0.216 deploy
